### PR TITLE
FEATURE: RAIL-3086 Add initial setup of gooddata-ui-apidocs

### PR DESCRIPTION
**Pull request by Tulean**

### CODE REVIEW

**Review by lupko — APPROVED** [review]
LGTM

**Comment by chiendm** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/1/ : FAILURE in 1m 23s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/1/ : FAILURE in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/1/ : SUCCESS in 19s

**Review by lupko — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/2/ : FAILURE in 1m 47s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/2/ : FAILURE in 7m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/2/ : SUCCESS in 1m 04s

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR1

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR1

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/3/ : FAILURE in 1m 32s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/7/ : SUCCESS in 4m 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/3/ : SUCCESS in 17s

**Pull request merged**
