### PR TITLE
RELATED: RAIL-3048 remove v8.4.0, fix visuals

### PR DESCRIPTION
**Pull request by no23reason**
* Remove sub-par version 8.4.0
* Fix version picker visuals so that they are in line with the Documentation site

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR10

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/16/ : SUCCESS in 40s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/21/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/16/ : SUCCESS in 24s

**Pull request merged**
