### PR TITLE
RELATED: RAIL-3511 prepare the library for publication

### PR DESCRIPTION
**Pull request by no23reason**
* sync the visuals with gooddata-ui (mainly applying https://github.com/gooddata/gooddata-ui/pull/391)
* add disclaimer to the initial page stating that the content is generated
* re-generate the vNext to be able to preview it "publicly"

JIRA: RAIL-3511

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR6

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/12/ : FAILURE in 2m 21s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/17/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/12/ : SUCCESS in 18s

**Pull request merged**
