### PR TITLE
RELATED: RAIL-3086 Remove package links from version index

### PR DESCRIPTION
**Pull request by Tulean**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR3

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/9/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/14/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/9/ : SUCCESS in 20s

**Pull request merged**
