### PR TITLE
RELATED: TNT-444 Update GD logo and graphics

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR13

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/19/ : SUCCESS in 59s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/24/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/19/ : SUCCESS in 18s

**Pull request merged**
