### PR TITLE
RELATED: RAIL-3998 migrate older versions to the new DocSearch

### PR DESCRIPTION
**Pull request by no23reason**
Follow up to #15, this migrates also the older versions from the legacy DocSearch to the new one.

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR16

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/22/ : SUCCESS in 2m 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/27/ : SUCCESS in 1m 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/22/ : SUCCESS in 20s

**Pull request merged**
