### PR TITLE
RELATED: RAIL-3086 Update search config to filter search based on ver…

### PR DESCRIPTION
**Pull request by Tulean**
…sion

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR5

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/11/ : FAILURE in 2m 53s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/16/ : SUCCESS in 1m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/11/ : SUCCESS in 23s

**Pull request merged**
