### PR TITLE
RELATED: RAIL-3048 fix and improve version picker

### PR DESCRIPTION
**Pull request by no23reason**
* fix the logic of choosing the latest version
* add link to both documentation and API reference in the version picker

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR9

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul-el7/15/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/20/ : SUCCESS in 55s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/15/ : SUCCESS in 22s

**Pull request merged**
